# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.

# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64|ARM'
  buildConfiguration: 'Release'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'

steps:


- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

